const OWNER_ROLE = 'restaurant_owner'

const ORDER_STATUSES = {
  PLACED: 'PLACED',
  ACCEPTED: 'ACCEPTED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
}

const RESTAURANT_STATUSES = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  MANUALLY_CLOSED: 'MANUALLY_CLOSED',
  TEMPORARILY_UNAVAILABLE: 'TEMPORARILY_UNAVAILABLE',
}

const ORDER_STATUS_ALIASES = {
  placed: ORDER_STATUSES.PLACED,
  accepted: ORDER_STATUSES.ACCEPTED,
  preparing: ORDER_STATUSES.PREPARING,
  ready_for_pickup: ORDER_STATUSES.READY_FOR_PICKUP,
  picked_up: ORDER_STATUSES.READY_FOR_PICKUP,
  out_for_delivery: ORDER_STATUSES.OUT_FOR_DELIVERY,
  on_the_way: ORDER_STATUSES.OUT_FOR_DELIVERY,
  delivered: ORDER_STATUSES.DELIVERED,
  cancelled: ORDER_STATUSES.CANCELLED,
}

const ORDER_TRANSITIONS = {
  [ORDER_STATUSES.PLACED]: [ORDER_STATUSES.ACCEPTED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.ACCEPTED]: [ORDER_STATUSES.PREPARING, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.PREPARING]: [ORDER_STATUSES.READY_FOR_PICKUP, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.READY_FOR_PICKUP]: [ORDER_STATUSES.OUT_FOR_DELIVERY, ORDER_STATUSES.DELIVERED],
  [ORDER_STATUSES.OUT_FOR_DELIVERY]: [ORDER_STATUSES.DELIVERED],
  [ORDER_STATUSES.DELIVERED]: [],
  [ORDER_STATUSES.CANCELLED]: [],
}

const normalizeOrderStatus = (value) => {
  if (!value) {
    return null
  }

  if (ORDER_STATUSES[value]) {
    return value
  }

  return ORDER_STATUS_ALIASES[String(value).toLowerCase()] || null
}

module.exports = {
  OWNER_ROLE,
  ORDER_STATUSES,
  ORDER_TRANSITIONS,
  RESTAURANT_STATUSES,
  normalizeOrderStatus,
}
