const DELIVERY_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  ARRIVED_AT_RESTAURANT: 'ARRIVED_AT_RESTAURANT',
  PICKED_UP: 'PICKED_UP',
  REACHED_CUSTOMER: 'REACHED_CUSTOMER',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
}

const ORDER_DELIVERY_STATUSES = {
  PENDING: 'PENDING',
  READY_FOR_ASSIGNMENT: 'READY_FOR_ASSIGNMENT',
  ASSIGNED: 'ASSIGNED',
  ARRIVED_AT_RESTAURANT: 'ARRIVED_AT_RESTAURANT',
  PICKED_UP: 'PICKED_UP',
  REACHED_CUSTOMER: 'REACHED_CUSTOMER',
  CASH_COLLECTED: 'CASH_COLLECTED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
}

const ASSIGNMENT_STATUSES = {
  REQUESTED: 'REQUESTED',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  PICKED_UP: 'PICKED_UP',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
}

const DELIVERY_ROLE = 'delivery_partner'

const DELIVERY_STATUS_ALIASES = {
  ASSIGNED: ORDER_DELIVERY_STATUSES.ASSIGNED,
  ACCEPTED: ORDER_DELIVERY_STATUSES.ASSIGNED,
  ARRIVED_AT_RESTAURANT: ORDER_DELIVERY_STATUSES.ARRIVED_AT_RESTAURANT,
  AT_RESTAURANT: ORDER_DELIVERY_STATUSES.ARRIVED_AT_RESTAURANT,
  REACHED_RESTAURANT: ORDER_DELIVERY_STATUSES.ARRIVED_AT_RESTAURANT,
  PICKED_UP: ORDER_DELIVERY_STATUSES.PICKED_UP,
  ON_THE_WAY: ORDER_DELIVERY_STATUSES.REACHED_CUSTOMER,
  ARRIVING: ORDER_DELIVERY_STATUSES.REACHED_CUSTOMER,
  AT_CUSTOMER: ORDER_DELIVERY_STATUSES.REACHED_CUSTOMER,
  REACHED_CUSTOMER: ORDER_DELIVERY_STATUSES.REACHED_CUSTOMER,
  CASH_COLLECTED: ORDER_DELIVERY_STATUSES.CASH_COLLECTED,
  DELIVERED: ORDER_DELIVERY_STATUSES.DELIVERED,
  CANCELLED: ORDER_DELIVERY_STATUSES.CANCELLED,
}

const DELIVERY_STATUS_TRANSITIONS = {
  [ORDER_DELIVERY_STATUSES.PENDING]: [
    ORDER_DELIVERY_STATUSES.READY_FOR_ASSIGNMENT,
    ORDER_DELIVERY_STATUSES.ASSIGNED,
    ORDER_DELIVERY_STATUSES.CANCELLED,
  ],
  [ORDER_DELIVERY_STATUSES.READY_FOR_ASSIGNMENT]: [
    ORDER_DELIVERY_STATUSES.ASSIGNED,
    ORDER_DELIVERY_STATUSES.CANCELLED,
  ],
  [ORDER_DELIVERY_STATUSES.ASSIGNED]: [
    ORDER_DELIVERY_STATUSES.ARRIVED_AT_RESTAURANT,
    ORDER_DELIVERY_STATUSES.CANCELLED,
  ],
  [ORDER_DELIVERY_STATUSES.ARRIVED_AT_RESTAURANT]: [
    ORDER_DELIVERY_STATUSES.PICKED_UP,
    ORDER_DELIVERY_STATUSES.CANCELLED,
  ],
  [ORDER_DELIVERY_STATUSES.PICKED_UP]: [
    ORDER_DELIVERY_STATUSES.REACHED_CUSTOMER,
    ORDER_DELIVERY_STATUSES.CANCELLED,
  ],
  [ORDER_DELIVERY_STATUSES.REACHED_CUSTOMER]: [
    ORDER_DELIVERY_STATUSES.CASH_COLLECTED,
    ORDER_DELIVERY_STATUSES.DELIVERED,
    ORDER_DELIVERY_STATUSES.CANCELLED,
  ],
  [ORDER_DELIVERY_STATUSES.CASH_COLLECTED]: [
    ORDER_DELIVERY_STATUSES.DELIVERED,
    ORDER_DELIVERY_STATUSES.CANCELLED,
  ],
  [ORDER_DELIVERY_STATUSES.DELIVERED]: [],
  [ORDER_DELIVERY_STATUSES.CANCELLED]: [],
}

module.exports = {
  DELIVERY_STATUSES,
  ORDER_DELIVERY_STATUSES,
  ASSIGNMENT_STATUSES,
  DELIVERY_ROLE,
  DELIVERY_STATUS_ALIASES,
  DELIVERY_STATUS_TRANSITIONS,
}
