// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/addresses" | "/admin" | "/admin/analytics" | "/admin/approvals" | "/admin/customers" | "/admin/dashboard" | "/admin/delivery-partners" | "/admin/live-map" | "/admin/login" | "/admin/orders" | "/admin/payments" | "/admin/promotions" | "/admin/restaurants" | "/admin/restaurants/[id]/menu" | "/admin/settings" | "/admin/support" | "/cart" | "/checkout" | "/delivery/active-order" | "/delivery/dashboard" | "/delivery/earnings" | "/delivery/incentives" | "/delivery/login" | "/delivery/more" | "/delivery/orders" | "/delivery/profile" | "/delivery/register" | "/delivery/shifts" | "/delivery/signup" | "/favorites" | "/help" | "/login" | "/orders" | "/profile" | "/profile/addresses" | "/profile/app-settings" | "/profile/favorites" | "/profile/help" | "/profile/settings" | "/restaurant-auth" | "/restaurant/[id]" | "/restaurant/categories" | "/restaurant/dashboard" | "/restaurant/menu" | "/restaurant/orders" | "/restaurant/settings" | "/restaurants" | "/rider-auth" | "/signup" | "/verify-otp"
type AppRouteHandlerRoutes = "/api/upload/image"
type PageRoutes = "/_document"
type LayoutRoutes = "/" | "/admin" | "/delivery" | "/profile"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_document": {}
  "/addresses": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/approvals": {}
  "/admin/customers": {}
  "/admin/dashboard": {}
  "/admin/delivery-partners": {}
  "/admin/live-map": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/payments": {}
  "/admin/promotions": {}
  "/admin/restaurants": {}
  "/admin/restaurants/[id]/menu": { "id": string; }
  "/admin/settings": {}
  "/admin/support": {}
  "/api/upload/image": {}
  "/cart": {}
  "/checkout": {}
  "/delivery": {}
  "/delivery/active-order": {}
  "/delivery/dashboard": {}
  "/delivery/earnings": {}
  "/delivery/incentives": {}
  "/delivery/login": {}
  "/delivery/more": {}
  "/delivery/orders": {}
  "/delivery/profile": {}
  "/delivery/register": {}
  "/delivery/shifts": {}
  "/delivery/signup": {}
  "/favorites": {}
  "/help": {}
  "/login": {}
  "/orders": {}
  "/profile": {}
  "/profile/addresses": {}
  "/profile/app-settings": {}
  "/profile/favorites": {}
  "/profile/help": {}
  "/profile/settings": {}
  "/restaurant-auth": {}
  "/restaurant/[id]": { "id": string; }
  "/restaurant/categories": {}
  "/restaurant/dashboard": {}
  "/restaurant/menu": {}
  "/restaurant/orders": {}
  "/restaurant/settings": {}
  "/restaurants": {}
  "/rider-auth": {}
  "/signup": {}
  "/verify-otp": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/delivery": never
  "/profile": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
