// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/admin/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/delivery-partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery-partners">> = Specific
  const handler = {} as typeof import("../../src/app/admin/delivery-partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/live-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/live-map">> = Specific
  const handler = {} as typeof import("../../src/app/admin/live-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/marketing/banners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing/banners">> = Specific
  const handler = {} as typeof import("../../src/app/admin/marketing/banners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/promotions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/promotions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/promotions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/restaurants/[id]/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/restaurants/[id]/menu">> = Specific
  const handler = {} as typeof import("../../src/app/admin/restaurants/[id]/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/restaurants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/restaurants">> = Specific
  const handler = {} as typeof import("../../src/app/admin/restaurants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../src/app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/active-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/active-order">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/active-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/earnings">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/incentives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/incentives">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/incentives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/login">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/more/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/more">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/more/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/orders">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/profile">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/register">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/shifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/shifts">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/shifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/signup">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../src/app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/profile/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/app-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/app-settings">> = Specific
  const handler = {} as typeof import("../../src/app/profile/app-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/profile/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/help">> = Specific
  const handler = {} as typeof import("../../src/app/profile/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/settings">> = Specific
  const handler = {} as typeof import("../../src/app/profile/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurant-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant-auth">> = Specific
  const handler = {} as typeof import("../../src/app/restaurant-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurant/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/restaurant/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurant/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/categories">> = Specific
  const handler = {} as typeof import("../../src/app/restaurant/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurant/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/restaurant/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurant/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/menu">> = Specific
  const handler = {} as typeof import("../../src/app/restaurant/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurant/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/orders">> = Specific
  const handler = {} as typeof import("../../src/app/restaurant/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurant/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant/settings">> = Specific
  const handler = {} as typeof import("../../src/app/restaurant/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurants">> = Specific
  const handler = {} as typeof import("../../src/app/restaurants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rider-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider-auth">> = Specific
  const handler = {} as typeof import("../../src/app/rider-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-otp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-otp">> = Specific
  const handler = {} as typeof import("../../src/app/verify-otp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/image">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/delivery/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/delivery">> = Specific
  const handler = {} as typeof import("../../src/app/delivery/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
